### PR TITLE
Fetch matching recipes from ingredients

### PR DESCRIPTION
**Pull request by Jarwhal3**
-Slight modification to the dropdown logic so that it fetches the description and ID.
-Submitting after selecting an ingredient adds all that ingredient's data to the user's fridge
-The ingredients list displays fine but does not update until the page is refreshed
-There's a "Get Matching Recipes" button. Right now it generates a list of recipes that use ingredients you have. Next up I will make a button that restricts the list to only show recipes that you have all the ingredients for.
-Right now it still uses my const userID logic instead of the usertoken, because of the aforementioned bug. I will update once that gets fixed though!

### CODE REVIEW

**Comment by Jonathan-PSU** [comment]
-Slite modification to the dropdown logic so that it fetches the description and ID.
-Submitting after selecting an ingredient adds all that ingredient's data to the user's fridge
-The ingredients list displays fine but does not update until the page is refreshed
-There's a "Get Matching Recipes" button. *Right now* it generates a list of recipes that use ingredients you have. Next up I will make a button that restricts the list to only show recipes that you have *all* the ingredients for.
-Right now it still uses my const userID logic instead of the usertoken, because of the aforementioned bug. I will update once that gets fixed though!

**Comment by adamstag20** [comment]
I really like the find recipe feature you made. I think we will need to try to find a way to make it more distinct the difference between browsing and your feature but it works greats. I'm having a hard time adding ingredients to my accounts fridge. Every time I add don't see my ingredients even after render. Salmon is the only ingredient that keeps showing on the page. I see from the logic you have my userID is grabbed but its not grabbing the ingredients associated with it.

**Comment by nayamairena** [comment]
The fixes look good, thank you for doing those.
I also am struggling to add ingredients and I am not sure why, I think it might have to do with the back end.

**Comment by adamstag20** [comment]
The global UserId doesn't seem to be changing even after the call to change in loginPage. My local storage token of the userId should work as replacement. I will get that finished and file a pull request.

**Pull request merged**
